Sugestão de boilerplate
idvogados/backend pull request #17
Opened 2020-05-03 18:21 UTC by pabrrs

### Descrição das Mudanças ###

Sugestão para estrutura do projeto

### *Bugs* Corrigidos ###

### Mudanças na API ###

### Mudanças de comportamento ###

### Testing Procedure ###

### PR Checklist ###

- [ ] Possui testes (se não, por favor descreva o motivo de não ter teste)
- [ ] Foi feito Rebase para a master no momento que o PR foi aberto
- [ ] Modificações estão de acordo com o padrão de código
- [ ] Atualizado documentação

### PR Checklist  do time ###

- [ ] O PR está apontando para a branch correta
- [ ] Os testes estão passando (ou as falha não são relacionadas a este PR)

2020-05-05 13:07 UTC, rodrigondec requested changes
Obrigado pela contribuição.

Comentei algumas duvídas e sugestões.

Mas gostaria de ressaltar que meu Review não deve ser tomado como indicativo de que todos os códigos JS estão ok :confused:

2020-05-05 13:07 UTC, rodrigondec commented on .docker/node-dev.Dockerfile
> +CMD ["npm", "start"]
Eu costumo colocar um entrypoint para esperar o DB estar online. Mas não é nada primordial.

2020-05-05 13:07 UTC, rodrigondec commented on docs/configuracoes.md
> +
Acredito que @Netaum adicionou algumas coisas com relação à isso em algum canto no PR dele.

Agora que você criou esse arquivo acredito que as instalações das libs necessárias para rodar podem ficar nele.

Com guias de instalação para
- nvm
- docker
- docker-compose

2020-05-05 13:07 UTC, rodrigondec commented on .mocharc.yaml
> +exit: true
Seguiremos com o Mocha? 

Ou teremos outro PR posterior para trocar pelo Jest?

2020-05-05 13:07 UTC, rodrigondec commented on .docker/node-prod.Dockerfile
> +CMD ["npm", "start"]
Se esse arquivo irá subir para produção é melhor utilizar um build de dois estágio (se pudermos comprimir mais o 'compilado') e trocar o usuário que está rodando a aplicação.

Tenho [esse exemplo de um Dockerfile trocando o usuário](https://github.com/rodrigondec/drf-api-domain/blob/master/Dockerfile).

2020-05-06 03:22 UTC, pabrrs commented on .mocharc.yaml
> +exit: true
Acredito que podemos começar com o mocha e posteriormente mudar para o Jest, caso seja essa a decisão tomada na issue #18 e nessa PR.

2020-05-06 03:24 UTC, pabrrs commented on .docker/node-prod.Dockerfile
> +CMD ["npm", "start"]
Acho bacana, podemos ter sim.
Como não foquei muito no Dockerfile, pois pegarei das sugestões do @Netaum, acho que podemos usar a PR #16 como parametro.

O que acha ?

2020-05-06 04:02 UTC, pabrrs commented on docs/configuracoes.md
> +
Adicionei suas sugestões https://github.com/idvogados/backend/pull/17/commits/d660ad48966bf164b33cd71357949ea0a3858ac5.

Deixei dois `TODO` para completar com a instalação do docker e rodar com make que o @Netaum está fazendo na PR #16.

Assim que finalizarmos lá, eu complemento aqui e decidimos em qual arquivo vai ficar e tudo mais.

2020-05-24 15:42 UTC, pabrrs commented
Foram adicionadas as sugestões da pr #16, feitas pelo @Netaum.

@idvogados/backend

2020-05-25 12:07 UTC, rodrigondec commented on .docker/node-prod.Dockerfile
> +CMD ["npm", "start"]
Concordo

2020-05-26 01:05 UTC, pictos commented
Acredito que estamos quase a ponto de fazer o merge desse PR! 🎉
Combinamos que os commits deste repositório serão em português... Sim eu sei que fiz alguns em inglês (shame on me), mas a partir daqui gostaria de ser mais atencioso em relação a isso.
@pabrrs , para reescrever seu commit (pode ser dentro de um só, com todas as modificações daqui) rode esse comandos na sua branch local:

git reset --soft d0b5e16

isso vai voltar sua branch pro meu último commit, sem excluir as suas modificações, depois disso é só refazer o commit tomando cuidado para colocar as mensagens em português. Ai deixo ao seu critério, se você quer fazer apenas um commit com tudo ou se quer dividir em commits menores.

Qualquer dúvida, por favor me avise, ficarei feliz em ajudar!

2020-05-26 14:42 UTC, pabrrs commented
@pictos Obrigado pelas instruções, por questão de costume acabo commitando tudo em inglês :sweat: Vou me policiar para evitar isso no projeto.

As alterações solicitadas foram implementadas :tada:

2020-05-29 23:27 UTC, merged