Created CONTRIBUTING.md
idvogados/backend pull request #3
Opened 2020-04-26 06:09 UTC by pedrocecchetti

### Descrição das Mudanças ###
Criei o arquivo CONTRIBUTING.md
Como a descrição na issue não era profunda, não sabia como fazer algo mais completo. Mas como estou de verdade empolgado com o projeto, bem... ahahaha

- Relacionado a issue #1 
**Tenha certeza de que existe uma issue aberta neste repositório para esta funcionalidade antes de enviar o PR**

### Mudanças na API ###

*Nenhuma*

### Mudanças de comportamento ###

*Nenhuma*

### Testing Procedure ###

*Nenhum*

### PR Checklist ###
- [ ] Possui testes (se não, por favor descreva o motivo de não ter teste)
- [ ] Foi feito Rebase para a master no momento que o PR foi aberto
- [ ] Modificações estão de acordo com o padrão de código
- [x] Atualizado documentação

### PR Checklist  do time ###

- [ ] O PR está apontando para a branch correta
- [ ] Os testes estão passando (ou as falha não são relacionadas a este PR)

2020-04-26 15:45 UTC, callesjuan submitted a review, later dismissed

2020-04-26 17:32 UTC, rodrigondec commented on CONTRIBUTING.md
> +O projeto hoje está dividido em 2 repositórios, o [**frontend**](https://github.com/idvogados/frontend) e o [**backend**](https://github.com/idvogados/backend) os passos a passos abaixo são idênticos
Cada projeto terá seu próprio contributing. 

Pode ser que os requisitos para contribuir com o backend seja diferente do frontend e assim por diante.

Remove essa parte mencionando o projeto em 2 repositórios e que os passos serão identicos (mesmo que por enquanto iremos duplicar esse arquivo no outro repo)

2020-04-26 18:05 UTC, rodrigondec commented on CONTRIBUTING.md
> +   5- Em **base fork** selecione o repositório e a branch **_para a qual você deseja subir as alterações_**
Todo PR deverá ser aberto para a branch padrão do repositório (no caso a branch `dev`)

2020-04-26 18:07 UTC, rodrigondec commented
@pedrocecchetti 

Não tinha prestado atenção à um delathe que me escapou. 

Atualiza o reeadme colocando um heading assim:

# Como contribuir
Leia nosso guia de contribuição nesse arquivo (link para o contributing)

2020-04-26 18:38 UTC, pictos requested changes
@pedrocecchetti, muito obrigado pelo primeiro PR ao projeto🚀!
Apenas algumas sugestões de alterações, sinta-se livre para discordar e fazer perguntas. 

Mais uma vez muito obrigado❣️

2020-04-26 18:38 UTC, pictos commented on CONTRIBUTING.md
> +Para contribuir com o projeto é necessário identificar issues que ainda estão abertas para aí sim abrir um PR. O passo a passo de como forkar o repositório e como abrir um PR seguem abaixo.
Acredito que o termo forkar não é muito bom, eis minha sugestão.
```suggestion
Para contribuir com o projeto é necessário identificar issues que ainda estão abertas para aí sim abrir um PR. O passo a passo de como fazer um *fork* o repositório e como abrir um PR seguem abaixo.
```

2020-04-26 18:38 UTC, pictos commented on CONTRIBUTING.md
> +1. ### **Como forkar o Repositório**
Como essa linha já possui as tags #, não precisa dos asteriscos.
```suggestion
1. ### Como forkar o Repositório
```

2020-04-26 18:38 UTC, pictos commented on CONTRIBUTING.md
> +   1- Inicialmente é necessário fazer as alterações de código dentro do seu repositório forkado localmente, em uma nova branch.
Acho que podemos remover o termo forkado aqui tbm, o que vc acha?
```suggestion
   1- Inicialmente é necessário fazer as alterações de código dentro do seu repositório localmente, em uma nova branch.
```

2020-04-26 18:38 UTC, pictos commented on CONTRIBUTING.md
> +   2- Assim que o processo de fork for finalizado você será redirecionado para o seu repositório que foi forkado a partir do idvogados.
```suggestion
   2- Assim que o processo de fork for finalizado você será redirecionado para a sua cópia do repositório a partir do idvogados.
```

2020-04-26 18:38 UTC, pictos commented on CONTRIBUTING.md
> +   4- Na página de comparação(Compare Changes), selecionar **compare across forks**.
Como é um termo em inglês sugiro que fique em itálico.
```suggestion
   4- Na página de comparação(_Compare Changes_), selecionar **compare across forks**.
```

2020-04-26 19:29 UTC, pabrrs commented on CONTRIBUTING.md
> +   7- Adicione uma descrição e um Título para o seu PR
Acredito que aqui deve recomendar para usar o template de [pull request](https://github.com/idvogados/backend/blob/dev/.github/PULL_REQUEST_TEMPLATE.md) que foi criado para o projeto.
```suggestion
   7- Preencha os campos necessários para criar uma PR, seguindo modelo do template.
```

O que acha ?

2020-04-26 19:40 UTC, rodrigondec requested changes
Apenas algumas sugestões de alterações, sinta-se livre para discordar e fazer perguntas.

Mais uma vez muito obrigado❣️

Você poderia também atualizar o `README.md` colocando um heading assim?

Seria bom deixar isso no readme do projeto

```
# Como contribuir
Leia nosso guia de contribuição nesse arquivo (link para o contributing)
```

2020-04-26 19:40 UTC, rodrigondec commented on CONTRIBUTING.md
> +O projeto hoje está dividido em 2 repositórios, o [**frontend**](https://github.com/idvogados/frontend) e o [**backend**](https://github.com/idvogados/backend) os passos a passos abaixo são idênticos
Cada projeto terá seu próprio contributing.

Pode ser que os requisitos para contribuir com o backend seja diferente do frontend e assim por diante.
Acho melhor remover essa parte (mesmo que por enquanto iremos duplicar esse arquivo no outro repo)
```suggestion

```

2020-04-26 19:40 UTC, rodrigondec commented on CONTRIBUTING.md
> +   5- Em **base fork** selecione o repositório e a branch **_para a qual você deseja subir as alterações_**
Irá ser decidido ainda. Com relação à outros procedimentos/restrições decididos pelos tech leads.

Mas por enquanto todo PR deverá ser aberto para a branch padrão do repositório (no caso a branch dev)
```suggestion
   5- Em **base fork** selecione o repositório e a branch **_dev_**
```

2020-04-26 22:17 UTC, pedrocecchetti commented on CONTRIBUTING.md
> +Para contribuir com o projeto é necessário identificar issues que ainda estão abertas para aí sim abrir um PR. O passo a passo de como forkar o repositório e como abrir um PR seguem abaixo.
Pensei exatamente nisso na hora que estava escrevendo, mas preferi deixar assim e descobrir as opiniões de outras pessoas. :)

2020-04-26 22:17 UTC, pedrocecchetti commented on CONTRIBUTING.md
> +1. ### **Como forkar o Repositório**
Justo

2020-04-26 22:17 UTC, pedrocecchetti commented on CONTRIBUTING.md
> +   1- Inicialmente é necessário fazer as alterações de código dentro do seu repositório forkado localmente, em uma nova branch.
Acho uma ótima

2020-04-26 22:20 UTC, pedrocecchetti commented on CONTRIBUTING.md
> +   7- Adicione uma descrição e um Título para o seu PR
Acho uma ótima! Mas como ao criar o PR o modelo já está inserido no campo de descrição, podemos só instruir para preenchê-lo corretamente!

2020-04-26 22:21 UTC, pedrocecchetti commented on CONTRIBUTING.md
> +O projeto hoje está dividido em 2 repositórios, o [**frontend**](https://github.com/idvogados/frontend) e o [**backend**](https://github.com/idvogados/backend) os passos a passos abaixo são idênticos
Ótimo, como disse, mesmo sem muitas especificações preferi mandar o pr para poder já começar a participar! :)

2020-04-26 22:22 UTC, pedrocecchetti commented on CONTRIBUTING.md
> +O projeto hoje está dividido em 2 repositórios, o [**frontend**](https://github.com/idvogados/frontend) e o [**backend**](https://github.com/idvogados/backend) os passos a passos abaixo são idênticos
E faz sentido ter especificações de contribuição diferentes, concordo com a decisão!

2020-04-26 22:22 UTC, pedrocecchetti commented on CONTRIBUTING.md
> +   5- Em **base fork** selecione o repositório e a branch **_para a qual você deseja subir as alterações_**
Ótimo! Deixa comigo que vou alterar

2020-04-26 22:23 UTC, pictos commented on CONTRIBUTING.md
> +   1- Inicialmente é necessário fazer as alterações de código dentro do seu repositório forkado localmente, em uma nova branch.
Só apertar no botão para fazer o commit então (;

2020-04-26 22:35 UTC, pedrocecchetti commented
Vou fazer as alterações e envio amanhã, ok?

2020-04-26 23:03 UTC, pictos commented
@pedrocecchetti, só pra garantir que vc não ter retrabalho, as sugestões que fizemos, utilizando o recurso de `Suggestion` (As que tem uma preview da alteração com um botão `Commit suggestion`) podem ser alteradas apenas clicando neste botão e fazendo o commit. Assim vc economiza tempo 😉

2020-04-26 23:14 UTC, pedrocecchetti commented
> @pedrocecchetti, só pra garantir que vc não ter retrabalho, as sugestões que fizemos, utilizando o recurso de `Suggestion` (As que tem uma preview da alteração com um botão `Commit suggestion`) podem ser alteradas apenas clicando neste botão e fazendo o commit. Assim vc economiza tempo 😉

Boa! Não vi, pq tô no app. Que por sinal me surpreendeu positivamente! Hahahaha:)

2020-04-27 12:56 UTC, pabrrs commented on CONTRIBUTING.md
> +   7- Adicione uma descrição e um Título para o seu PR
@pedrocecchetti maravilha, acho uma boa.

2020-04-27 20:31 UTC, rodrigondec approved these changes

2020-04-27 22:00 UTC, pictos approved these changes

2020-04-27 22:00 UTC, merged